### ISSUE TITLE
responsive icon-bar

### ISSUE THREAD

**Issue by ghost** [jesselau76/hugo-w3-simple#1]
This theme is so fast! Page loads are so quick and I like that it minimises uses of javascript packages as it helps the website be easy to maintain over time.

The icon-bar stretches all the way across the bottom of the screen when the page is resized - are you happy with it this way? I might modify it on my own site so that each icon is a similar size to how it looks on a full size desktop. Thought I'd raise the issue in case you thought this would be something others might like too - feel free to close it if you disagree.

<img width="958" alt="screenshot 2018-11-21 at 15 10 28" src="https://user-images.githubusercontent.com/22416807/48850217-15238600-eda0-11e8-8338-a947101c11ed.png">

**Comment by jesselau76** [comment]
Thanks for opening the issue. I am new to github with team work. So if I have something wrong please bear with me a little.

Yes. I designed the icon bar with responsive style. If the width is less than 1024 then it displayed on the bottom because the w3-content is 980px width. To make sure the icon bar does not disturb the main content, I designed so.

Feel free to modify it. I am open to any design with this theme. Thanks.

**Comment by ghost** [comment]
Don't worry - its great you keep your design minimal and open to customisation. I really enjoyed trying your theme, it's always helpful to see new ideas for a website.
